# Generated by Django 4.0.5 on 2022-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_resources_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
