# Generated by Django 4.0.5 on 2022-06-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/picstu.jpg', upload_to='profile'),
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
    ]
