# Generated by Django 4.0.5 on 2022-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_instructor_profile_pic_delete_instructorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
