# Generated by Django 4.0.5 on 2022-06-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_alter_instructor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='post_time',
            field=models.DateTimeField(max_length=100),
        ),
    ]
