# Generated by Django 4.0.5 on 2022-06-12 04:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_remove_submission_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('Submission', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.submission')),
            ],
        ),
    ]
