# Generated by Django 4.0.5 on 2022-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='student@bic.edu.np', max_length=256),
        ),
    ]
